### ISSUE TITLE
Add an option to show unchanged lines for more context

### ISSUE THREAD

**Issue by shiv15** [AXeL-dev/ngx-diff2html#40]
It would be nice to have an option to get more number of unchanged lines. Something like this:
<img width="1350" alt="Screenshot 2023-11-08 at 1 59 06 PM" src="https://github.com/AXeL-dev/ngx-diff2html/assets/13417274/6200cad3-f633-4d58-84ec-d3ad34a67edb">

Upon clicking, the option should load the unchanged lines.

**Comment by AXeL-dev** [comment]
Do you have an idea if this is available in [diff2html](https://diff2html.xyz/) ? if it is the case, the option can be easily added to the `<ngx-diff2html>` component, if not it should be first implemented in the `diff2html` library before being included in this package.

**Comment by shiv15** [comment]
Makes sense. There are a couple of issues for it in which the author is stating that since he does not have the context of the code that will be passed on it should be worked on from the outside.

The primary issue that I am facing here is that we do not get any context lines at all. I was thinking for this project perhaps we could get more lines at the start and the end of the diff to get more context. I can start working on this.

The issues in the diff2html for reference:
https://github.com/rtfpessoa/diff2html/issues/207
https://github.com/rtfpessoa/diff2html/issues/406

**Comment by AXeL-dev** [comment]
I think that we should also look at the [diff-match-patch](https://github.com/google/diff-match-patch) library & check if there is a way to get more context so we can pass it to the diff2html parser.

**Comment by shiv15** [comment]
I checked the diff-match-patch library. Apparently, this is a common issue for the library. In the wiki, they have mentioned that they have something called rolling context which cause it. This happens when we use the `patch_make` function, the equality (0) string is reduced from that function. There is no API to get more context for that function.

I suggest two of the following things:

- For now we can add an option flag `showContext` if the user wants to display the context with the diffs. This displays all the equality lines from the diffs.
- I can create another issue with the diff2html to add UI for more context lines and we add the logic for it. I have a function ready for it.

Please let me know your thoughts.

**Comment by AXeL-dev** [comment]
> #41 created PR for this issue.

First of all sorry for the late reply, i didn't notice your replies ><, & well, thank you for the PR, i've merged it! kudos :tada: 

I'll close the issue.
